// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Express = require("bs-express/src/Express.bs.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

var route = Express.Router.make(undefined, undefined, undefined, undefined);

Express.Router.get(route, "/:username", Express.Middleware.from(function (param, req, res) {
          var params = Express.$$Request.params(req);
          var targetUser = Js_dict.get(params, "username");
          console.log(targetUser);
          var renderDict = {};
          renderDict["title"] = "Rescript and Express+Pug";
          if (targetUser !== undefined) {
            renderDict["username"] = JSON.stringify(Caml_option.valFromOption(targetUser));
          } else {
            renderDict["username"] = "unkown";
          }
          return Express.$$Response.render("index", renderDict, undefined, res);
        }));

exports.route = route;
/* route Not a pure module */
