// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Mvc = require("./routes/Mvc.bs.js");
var Home = require("./routes/Home.bs.js");
var Express = require("bs-express/src/Express.bs.js");

var app = Express.App.make(undefined);

Express.App.set(app, "view engine", "pug");

Express.App.useRouterOnPath(app, "/", Home.route);

Express.App.useRouterOnPath(app, "/mvc", Mvc.route);

Express.App.listen(app, 3000, undefined, (function (param) {
        console.log("server run at http://localhost:" + 3000);
        
      }), undefined);

var port = 3000;

exports.app = app;
exports.port = port;
/* app Not a pure module */
